#
# THIS IS A SNAPSHOT VERSION
# OF BestTool! THIS IS NOT
# THE FINISHED PLUGIN
#


# When false, new players have to run /besttool or /bt once to enable BestTool
besttool-enabled-by-default: false

# When false, new players have to run /refill or /rf once to enable hotbar refill
refill-enabled-by-default: false

# Only use items from the hotbar
hotbar-only: true

# Don't use items if they are going to break with this usage
prevent-item-break: true

# The preferred slot where BestTool should move the tool if it's not in the hotbar.
# Must be a number between 0 (leftmost hotbar slot) and 8 (rightmost hotbar slot)
# NOT IMPLEMENTED YET
#favorite-slot: 8

# Whether to use gold tools
# NOT IMPLEMENTED YET
#use-gold-tools: false

# Show some infos on startup
verbose: true

# You probably don't want this
debug: false

# You probably don't want this - creates a .csv file containing a mapping between all Materials and their best tool
dump: false